CREATE TABLE product(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(23) NOT NULL UNIQUE,
    price DECIMAL(10, 2) DEFAULT 0.00,
    description VARCHAR(123) NOT NULL,
    imageUrl VARCHAR(23) NOT NULL UNIQUE
);